### ISSUE TITLE
is there any way that i can get component instance when BodyOutputType is Component?

### ISSUE THREAD

**Issue by anand514** [Stabzs/Angular2-Toaster#101]
i have a requirement like i have show some action buttons on toast , so i used BodyOutputType component, but i am unable to access the component that was created .

**Comment by Stabzs** [comment]
This is well documented in the tests. In addition, you can use this [plunker](http://plnkr.co/edit/Duc4JfIqsa4UnPRFq3pG?p=preview) as a guide.

**Comment by anand514** [comment]
Thanks for the quick response @Stabzs 
,
i did get what the plunker demo is suggesting, but my requirement is i need an **instance of an component that will create dynamically when BodyType is Component** , so according to the plunker example i need instance of **MaterialComponent** in the class **App**. 

My requirement is like in the class App i have to do something when button is clicked on the MaterialComponent, so some how if i get an instance of MaterialComponent, i can add callback to the material component and i can do my necessary action in the App component.

Once again thanks for the quick response.

**Comment by Stabzs** [comment]
@anand514 no problem, I'm happy to keep working through this with you (although I'm keeping this closed as a duplicate at the moment).

I highly recommend you read through this closed issue https://github.com/Stabzs/Angular2-Toaster/issues/84, since it is largely related to what you are trying to accomplish.

In `1.1.0`, the toast object was added to the instance of the dynamically rendered component.  In addition, `pop()` returns the toast instance.  I haven't tested it, but it should be possible to add behavior to MaterialComponent and allow that to update the toast instance which may be reflected back to the referenced toast in app.

However, I think you may be misunderstanding how components should work in Angular 2 (and how they're utilized when dynamically rendered).  Each component should be able to enforce its own state.  As a result, when you click a button in MaterialComponent, it should affect state in your material component.  If you need to share behavior, you should do so with a state/flux implementation or a shared service.  I'd recommend working through the plunker again and following the data flow to see how you can adapt it to your needs.

**Comment by anand514** [comment]
thanks for clear explanation @Stabzs , initially overlooked the plunker demo that you shared, but now i get it.

**Comment by Stabzs** [comment]
@anand514 my pleasure!
