### ISSUE TITLE
toasterConfig for toast is always overwritten

### ISSUE THREAD

**Issue by nabuk** [Stabzs/Angular2-Toaster#109]
https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toaster-container.component.ts#L99

Toast has toasterConfig property but it doesn't work - is always overwritten.

Possible fix: overwrite only if not provided.

**Comment by Stabzs** [comment]
The `toast.toasterConfig` property is an implementation detail that is exposed merely for convenience...it is NOT part of the API and this behavior is 100% intentional.  

Configuration changes should be made to one of two places, the global toasterConfig which affects all toasts, or parameterized options to toast object construction.  This presents a clearer API, although I agree that it is misleading that toasterConfig is exposed on the toast interface.  I may look at ways to make this an internal implementation detail and remove it completely from the interface since it is misleading.  

That said, all documentation will point to either of the two cases I outlined above...they will never use the toasterConfig property itself.  I hope that helps clear things up.
