### ISSUE TITLE
Show inside a container

### ISSUE THREAD

**Issue by matzrm** [Stabzs/Angular2-Toaster#141]
I would to show the toast inside a container, and not in a floating position inside the page. Is it possible?

**Comment by Stabzs** [comment]
Can you please a more concrete example of what you'd like to be able to do?

**Comment by matzrm** [comment]
For example, I want to show the alert upon a form, so not show it in the middle/top/bottom of the page but in a specific position.

**Comment by Stabzs** [comment]
@matzrm you could in theory embed a toast container directly in your form, although you'd then need to add positioning overrides to force it into the right location.  This level of customization probably wouldn't be driven by the library itself (since it isn't a common ask and it largely depends on the needs of the consumer) but it absolutely could be done by you if you styled it as such.
