### ISSUE TITLE
Multiple toaster containers: A single config is used for all toasts

### ISSUE THREAD

**Issue by karoliina** [Stabzs/Angular2-Toaster#144]
In my application I want to use two separate toaster containers, each of which has its own toaster config. I can then display toasts in a particular container by using the container ID I've assigned in its config object.

What happens, though, is that the toast object's config is always overwritten by the config of the `ToasterContainerComponent`  whose `addToast` method happens to be called last when a toast is popped. [This line](https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toaster-container.component.ts#L161) is the culprit.

Is there a reason why the toast's `toasterConfig` property is updated before the if block on lines 163-164? If the assignment on line 161 would be moved to be after this if block, I believe this wouldn't be an issue.

Am I misunderstanding something?

**Comment by Stabzs** [comment]
@karoliina I think there is some misunderstanding here.

The configuration of the container is added to the toast instance for easier internal tracking.  That said, you cannot pass container configuration via a toast.  Rather, there is a fairly sophisticated API for the ToasterService that allows a good deal of customized overrides the behavior of the container drawn from the toasterConfig.

The naming is tricky...in this case toasterConfig is referring to the toaster container instance, not the toast itself.

Is there a particular issue that you are trying to solve?

**Comment by karoliina** [comment]
I may have explained my use case badly, and have forked and edited your demo to show what I'm trying to do. See [here](https://github.com/karoliina/Angular2-Toaster/blob/fbbd80e4253072c83b4f9261059a4da223a0c2dd/demo/angular-cli/src/app/app.component.ts). When I run this demo, one of the toast titles should be blue and the other red, but they both show up in red.

I'm not trying to pass the container configuration via the toast itself, I just want to have two different containers with different configurations. I believe the container configuration is added to the toast just a little bit too early - wouldn't it make sense to only add it to the toast after it has been determined that the container ID's match? (Lines 163-164 in `toaster-container.component.ts`)

If you think it's okay to make this change, I can open a PR for it later today.

**Comment by Stabzs** [comment]
@karoliina thanks for the further explanation.

This may be due to some bad configuration code that should be fixed in 5.0.0-alpha.1.  Can you please upgrade against the alpha release and see if the issue still persists?  You can find setup instructions of the new release here: https://github.com/Stabzs/Angular2-Toaster/blob/5.x.x/Target_Angular_5/README.md

**Comment by Stabzs** [comment]
@karoliina Actually, after taking a closer look at your example, i don't see where you actually pull styles.css into your bundle.  Are you sure that the style is actually ever being applied?

**Comment by karoliina** [comment]
Thanks, I'll try with 5.0.0-alpha.1.

The CSS file is being included in `.angular-cli.json` [here](https://github.com/karoliina/Angular2-Toaster/blob/fbbd80e4253072c83b4f9261059a4da223a0c2dd/demo/angular-cli/.angular-cli.json#L23). When I run the example, both notification titles are red.

**Comment by Stabzs** [comment]
@karoliina I'll pull down your example and take a closer look in that case.  Thanks for confirming!

**Comment by karoliina** [comment]
Sounds good. Unfortunately 5.0.0-alpha.1 doesn't solve this - I've pushed a separate commit that upgrades Angular as well as angular2-toaster to the latest versions.

**Comment by Stabzs** [comment]
@karoliina I've identified the issue.  

Toasts that are broadcasted to multiple containers are actually still the same toast instance.  This is useful in cases where you want to update the returned toast and have that update be reflected in each toaster container toast instance.

However, in this case, two properties, titleClass and messageClass, truly need to be scoped to the container instead of the single toast instance, even though they're reflected in different html representations of the same toast object.

I've pushed enhancements up in the form of 5.0.0-beta.1 that demonstrates this and I've updated the demo/angular-cli project to match.  If you could retest the functionality against this version, it would be much appreciated.
