### ISSUE TITLE
Toast not show on errorHandler when error is throw by http request

### ISSUE THREAD

**Issue by gszumiec** [Stabzs/Angular2-Toaster#155]
Toast not show on errorHandler when error is throw by http request.

ErrorHandler implementation:

`import { ErrorHandler, Inject, Injectable } from '@angular/core';
import { NotificationService } from 'services/notification/notification.service';
import { HttpErrorResponse } from '@angular/common/http';
import { ToasterService } from 'angular2-toaster';

export class Message {
  name: string;
  message: string;
  details: string;

  constructor(
    name: string,
    message?: string,
    details?: string,
  ) {
    this.name = name;
    this.message = message;
    this.details = details;
  }
}

@Injectable()
export class GlobalErrorHandler implements ErrorHandler {

  constructor(private notificationService: NotificationService, private toasterService: ToasterService) {

  }

  handleHttpError(error: HttpErrorResponse): Message {
    let message = '';
    if (error.error && error.error.errors && error.error.errors.length > 0) {
      message = error.error.errors.reduce((agg, err) => agg + err.type || err.message);
    }

    return new Message(error.statusText, message);
  }

  handleTypeError(error: TypeError): Message {
    return new Message(error.name, error.message, error.stack);
  }

  handleError(error: any): void {
    let message: Message;
    if (!message && error instanceof HttpErrorResponse) {
      message = this.handleHttpError(error as HttpErrorResponse);
    }

    if (!message && error instanceof TypeError) {
      message = this.handleTypeError(error as TypeError);
    }

    if (error && error.rejection)  {
      message = this.handleHttpError(error.rejection as HttpErrorResponse);
    }

    if (!message) {
      message = new Message(error);
    }

    this.toasterService.pop(error, message.name, message.message);
    this.notificationService.error(message.name, message.message);
    this.showErrorInConsole(error);
  }

  private showErrorInConsole(error: any): void {
    if (console && console.group && console.error) {
      console.group('Error Log');
      console.error(error);
      console.error(error.message);
      console.error(error.stack);
      console.groupEnd();
    }
  }
}
`

Toast will show when I push back button on browser.

Same behavior on chrome and ie

**Comment by Stabzs** [comment]
I cannot reproduce this error and your example code is a bit convoluted so I can't run it verbatim.

If you can create a minimal git repo that fully reproduces the problem, I'll be happy to take a closer look at it.

**Comment by Rethary** [comment]
Hello I have the same issue if I will not fix it I will try to make you the small repo. But first question.

My issue is that when I use your code like in your examples it's ok. f.e.

private popToast() {
    var toast: Toast = {
      type: 'info',
      title: 'e',
      body: 'Here is a Toast Body',
      showCloseButton: true, 
    };

    this.toasterService.pop(toast);
  }

but when I use the same code in service not in component it do not work. It is normal behavior ? It should only work in the components ? 

Because the same like user that started this conversation (gszumiec) I used your code without component only in some export class.

app.component:
<toaster-container [toasterconfig]="toasterConfig"></toaster-container>

some export class (not component):
private popToast() {
    var toast: Toast = {
      type: 'info',
      title: 'e',
      body: 'Here is a Toast Body',
      showCloseButton: true, 
    };

    this.toasterService.pop(toast);
  }

**Comment by Stabzs** [comment]
@rethary thanks for looking into it further. There very well may be something in Angular's reactivity that is unaccounted for in the library since the focus is components first. That said, I would like to solve the issue if at all possible. Are you able to create either a minimal plunker or repo that demonstrates the behavior?

**Comment by dgsqrs** [comment]
I have the same problem after upgrading to angular 6. This is probably an rxjs related error no ?
