### ISSUE TITLE
tapOffToDismiss Config Suggestion

### ISSUE THREAD

**Issue by dougmolineux** [Stabzs/Angular2-Toaster#156]
Thank you for this useful module. We are using this to display an error message indefinitely (no timeout) with a greyed out background, but the components behind it are still clickable and functional. 

Ideally, if the user clicks anywhere on the screen (on or off the toast itself) we wanted to dismiss the toast. 

Perhaps there is another we could achieve this? Please advise,

Thanks again!

**Comment by Stabzs** [comment]
Glad you're finding the library useful!

This is a tough situation based on your current implementation.  You're essentially requiring that the toast be aware of click events outside of its context.

My recommendation would be to avoid this type of tight coupling.  Toasts should only be aware of their contexts and their toaster-containers should instead be responsible for handling anything that occurs outside of their localized context.

The `toasterService` will return the toast instance upon pop.  Typically I recommend letting the container handle the state of the toasts, but since you need to be able to trigger behavior from external state, you need to extend the state.

I'd recommend that wherever you pop the toast and display a greyed-out background, that you store that toast state and attach a click handler to that component instead:

```TypeScript
// component that handles "sticky" error message and background
private errorToast: Toast;

// display grey background

// pop toast and store the "state"
this.errorToast: Toast = this.toasterService.pop(toast);

click(event: MouseEvent) {
    event.stopPropagation();
    this.toasterService.clear(toast);        
}
```

This will effectively remove the state when the background (that you displayed) is popped.  This will give you far more control over the lifecycle of the toast as opposed to try to have the toast instance "guess".

Alternatively, you can always use a `BodyOutputType.Component` toast type that uses a shared service to listen to broadcasted events.  You can see a relatively close example of this technique here: http://plnkr.co/edit/GC3c9j?p=preview

**Comment by dougmolineux** [comment]
Thank you very much for your quick response! I will investigate these options and figure something out :)

👍

**Comment by Stabzs** [comment]
My pleasure!  Feel free to respond to this thread if you need additional clarification.
