### ISSUE TITLE
Toast is not displayed in AfterViewInit method

### ISSUE THREAD

**Issue by ddahan** [Stabzs/Angular2-Toaster#163]
I'm trying to pop a toast on a `ngAfterViewInit` method, without success.

**The code**

    @Component({
      selector: 'app-team-member-menu',
      templateUrl: './team-member-menu.component.html',
      styleUrls: ['./team-member-menu.component.css']
    })
    export class TeamMemberMenuComponent implements AfterViewInit {
    
      defaultToasterConfig = defaultToasterConfig;
    
      constructor(private toasterService: ToasterService) {}
    
      ngAfterViewInit() {
        console.log('entering view init');
        const toast: Toast = {
          type: 'success',
          body: 'I am init toast'
        };
        this.toasterService.pop(toast);
      }
    
      toto() {
        console.log('toto button clicked');
        const toast: Toast = {
          type: 'success',
          body: 'I am toto toast'
        };
        this.toasterService.pop(toast);
      }

**The behaviour**
(*Note: my toast lifetime is 5 seconds*)

 - After entering the view, I can see in the console the message "entering view init" but no toast, which is not expected.
 - And then, for example, if I click on button that triggers `toto()` in my template 2 sec after entering the view, I'll see toto toast for 5 seconds, **and** init toast for 3 seconds. 

This means the init toast bas been kind of triggered, but for some reason it was not displayed !?!

** Notes **
I'm running Angular 6.0.0 and rxjs-compat to ensure compatibility.

Any idea? Thanks.

**Comment by Stabzs** [comment]
This is most likely due to running Angular 6 against the library prior to upgrade.

I am in the middle of creating an Angular 6 target release and I'll test your scenario against it.

**Comment by Stabzs** [comment]
Please test this against the new 6.0.0 release and confirm if it is still an issue.  Thanks!

**Comment by ddahan** [comment]
Hi, 
After upgrading to 6.0.0, it still have the exact same problem.

**Comment by Stabzs** [comment]
Thanks for confirming. I’ll take a closer look.

**Comment by Stabzs** [comment]
I can't reproduce this in the angular-cli demo app.  AfterViewInit properly fires a toast and it display for the correct duration.  

Do you have a conflict where your `toaster-container` is being loaded in a sibling component or even AFTER `TeamMemberMenuComponent` is loaded?  You should always render your `toaster-container` as far up the component tree as possible and as early as possible so that you can target the container earlier rather than later.

In either case, I'll need a more detailed reproduction in order to identify the issue.
