### ISSUE TITLE
Placing custom bottom with method call in the toaster body

### ISSUE THREAD

**Issue by theunreal** [Stabzs/Angular2-Toaster#30]
I tried the following code:

```
var toast : Toast = {
				type: 'info',
				title: 'Check',
				body: 'Are you sure you want to do this?<br/><button md-button (click)="freeUser()">I'm sure</button>',
				bodyOutputType: BodyOutputType.TrustedHtml
				};
			this.toasterService.pop(toast);
```

Unfortunetly the click event not working, so my question is, if there is any way to make custom button with some action in a toast body?

**Comment by Stabzs** [comment]
Make sure you are using the most recent version `0.3.4-rc.1` since there were css changes that had to be made to prevent the image from overlaying the body and preventing click events.

`TrustedHtml` is not the correct `BodyOutputType` for any sort of eventing, because Angular 2 has not been made aware that there is anything to register.  It is simply rendering html.

You need to use the `Component` output type and encapsulate your current body into that component.  See [this demo](https://github.com/Stabzs/Angular2-Toaster/blob/master/demo/systemjs/src/app.ts#L223).
