### ISSUE TITLE
No Toaster Containers have been initialized to receive toasts.

### ISSUE THREAD

**Issue by tchoulihan** [Stabzs/Angular2-Toaster#36]
I'm using angular2-toaster with angular-2 rc.2, and I get this error above. I have an example set up exactly like that on the front page, with the `<toaster-container></toaster-container>` in the template.

**Comment by tchoulihan** [comment]
Never mind, figured out this one was because I was trying to do it on `ngOnInit`, instead of `ngAfterViewInit`.

**Comment by brianlowe** [comment]
I'm getting the same error reported in the console when I try to use pop(message: string), but I can't see anything in the docs telling me I need to initialize the container, or how I might do such a thing, or when.

tchoulihan is doing something in the ngAfterViewInit event, but what?

**Comment by Stabzs** [comment]
@brianlowe can you please provide a bit more context on what you are doing and how your code is structured?  Most likely you are calling pop from the constructor, before the container is rendered to the DOM.

**Comment by brianlowe** [comment]
@Stabz - thanks for a rapid response!

I'm just beginning with Angular2 (no experience of Angular 1) so my app is quite simple so far. I have a component with a clickable button wired to a handler that just raises an alert in the browser. Obviously that's not going to be testable so I need to replace it with a toaster.

So far I've added the `import { ... } from ... ` line at the head of my component, and added `providers: [ToasterService], directives: [ToasterContainerComponent]` in the \@Component decorator, and added `private _toasterService: ToasterService` as a constructor argument.

My layout includes `<body>
    <toaster-container></toaster-container>`

Now, in my button's click handler I replaced `alert("todo - act on this click");` with `this._toasterService.pop("todo - act on this click");` and as soon as I click the button I get this error in the browser tools console.

I can't see anything in the sources or in the test specs that might show me where I would initialize the toaster, so I don't know what I've missed.

**Comment by brianlowe** [comment]
Hmmm, my layout has the component's markup as a child of the <body> element, but in the examples the component's tag is always given inline with the calling element's template. Maybe the initialization I'm looking for is automatic when the toaster component is found and parsed within my view...  

I've tried moving my `<toaster-container>` tag to include it as part of the markup loaded by my component, but that raises a different error: **Template parse errors:
Can't bind to 'ngSwitchCase' since it isn't a known native property**

**Comment by Stabzs** [comment]
@brianlowe It is difficult to pin down the exact cause of the issues you are having without a plunker, so if you continue to have difficulties, please create one and I'd be happy to walk through it.  That said, here are a few observations:

- The pop call is incorrect and will cause issues.  The first argument for `pop()` is the toast type, not a title or body.  As a result, if it tries to map the string you've passed as a type, it'll certainly cause issues.  Perhaps better error handling can be added around this.
- Your setup of the actual container seems very reasonable and your inclusion of both the service and the container component looks perfect.  However, as you noted in your subsequent comment, the component markup IS inline with the calling element template.  This is for bootstrapping purposes in your Angular 2 app.  Angular 2 is a bit different in how it initializes and you need to make certain that the app is initialized before rendering subsequent components. 
- Now, this brings us to the next point...it looks like by moving your `<toaster-container>` inclusion to your template, you are now properly bootstrapping the library, which is great!  However, it looks like you have a mismatch in version.  Since angular2-toaster 0.3.5-rc.2, Angular 2.0.0-rc.2 or higher has been required due to changes in Angular 2's switch/case syntax.  As a result, please make sure you are using a current version of angular 2 (I recommend rc 3 or 4) or use a more deprecated version of angular2-toaster, which I don't recommend since I've made additional bug fixes in the last few versions.

If that doesn't help you get going, please feel free to create a plunker and I'll be more than happy to take a look and help you get it up and running.

**Comment by brianlowe** [comment]
@Stabzs Thanks for this. I've reworked my code a little so I now have the latest angular (rc4) and dependencies, and by passing the correct arguments in to the pop() method I can get a toast to appear in my page.

Now my problem is with the configuration.

When I include `[toasterConfig]="toasterConfig"` in my tag errors are thrown in `ng_class.ts` line 111 where it tries to trim a className but className is undefined. If I leave out the config and rely on the defaults, this line is hit several times with various class names, or empty strings, but never with undefined. If I use an empty toasterConfig, or one with all of its members populated I hit the same undefined className problem.

I've tried to set up a plunker to illustrate the problem, but that seems like another learning curve to struggle with right now. I get nowhere. 

I don't expect you to spend lots of time on this, but thanks for your help so far.

One other thing though... I wonder why pop's first argument accepts an argument of type `string | Toast` when there are only 5 usable string values. You could check the passed value at the start to make sure it's valid, but maybe it would be better to rely on TypeScript's typing by creating a `ToastType` enum as `info | wait | error | success | warning` and requiring the first argument to be `ToastType | Toast`.

**Comment by brianlowe** [comment]
So, if I create a config object with  
`this.toasterConfig = { positionClass: "toast-top-full-width" }` 
then TypeScript is happy because the object meets the ToasterConfig interface definition, but deep into the generated ToasterContainerComponent.template.js code it finds an array 
`["toast-top-full-width", undefined]` 
and passes each member to ng_class_toggleClass, which crashes out trying to apply .trim to the undefined className.

If I create a config object with 
`var cfg = new ToasterConfig(); 
cfg.positionClass = "toast-top-full-width"; 
this.toasterConfig = cfg;` 
then the array found in the generated code is
`["toast-top-full-width", ""]` 
and the ng_class._toggleClass code is OK with the empty string passed.

I now have a working setup. Yayy!
