### ISSUE TITLE
Icon class names

### ISSUE THREAD

**Issue by EricSch** [Stabzs/Angular2-Toaster#44]
I have a suggestion. 
Your icon classes are all named **icon-***
Would be possible to rename them to a more specific name?
Many font libraries out there are already using **icon-**, so there will be conflicts with existing class names. So I have now to rename your classes in our app.

Thanks

**Comment by Stabzs** [comment]
I understand the issue completely.  Thanks for bringing it up.

To clarify, the icons are VERY specific and they are exactly that...icon for the error case, icon for the success case, etc.

However, looking over the CSS, I noticed I failed to include any specificity on the icon classes, which is a complete miss and should be addressed.

This would fix the issue of the Angular2-Toaster css overwriting any values in any font library you would use.

Are you finding that you are running into the opposite issue?  Where the font library affects the Toaster styling?  If that's the case, once I fix the specificity you would simply need to reorder your CSS loading.

The names themselves are descriptive of what they are doing.  In addition, if I changed the names that would be a breaking change since consumers may have used the class names as they are today.

**Comment by EricSch** [comment]
Thanks for answering.
I understand that it would be a breaking change. as workaround for me, I could set my own classes, I think.
And I had the opposite, the toaster css was overwritten by the icon moon-fonts. They use also the classes like "moon icon-info", I need to check, if they have any specificity defined. This would be a fail.
