### ISSUE TITLE
NgModule Documentation not complete/right?

### ISSUE THREAD

**Issue by levjad** [Stabzs/Angular2-Toaster#51]
Maybe I'm missing something but I guess the documentation is wrong. First  you should import Component to use the @Component Annotation. Then it's always saying that ToasterModule "has no exportet member".

Am I missing something?

**Comment by Stabzs** [comment]
You are correct, component would need to be imported as well. I did not add that to the documentation because I didn't want to detract from the actual ngModule inclusions, but apparently that just caused confusion so I will update it. 

Make sure you are using the latest version: 0.4.0-rc.5. The previous version had an incorrectly build package. 

Finally, please see http://plnkr.co/edit/hkENUhos6q9fhiOHprXO?p=preview for a simple NgModule demo. It should help you get started. If you still have issues importing ToasterModuke, please create a plunker and I'll be happy to take a look.

**Comment by Stabzs** [comment]
@levjad There is a new build, `0.5.1-rc.6` that fixes an improper inclusion in `toaster.module`.  This may also resolve your issue if you are still running into difficulties.
