### ISSUE TITLE
Error: Unexpected value 'ToasterModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by robinkedia** [Stabzs/Angular2-Toaster#55]
When compiling with @Angular/Compiler-cli it throws Error: Unexpected value 'ToasterModule' imported by the module 'AppModule'

Angular 2 RC6
ngc -p tsconfig.json

**Comment by Stabzs** [comment]
Could you please provide more context around this error or a working, reproducible example?  Thanks

**Comment by dagstuan** [comment]
Can confirm this one. I have the same issue when I try to compile my project using AoT compilation. It seems Angular2-Toaster currently doesnt support AoT compiling. I'm not exactly sure why though.. will keep digging :)

**Comment by dagstuan** [comment]
I managed to get it to build by importing the source `toaster.module.ts` file instead of trying to import the one exported by the lib.

as in: `import { ToasterModule } from 'angular2-toaster/src/toaster.module';`.

So there seems to be something wrong with how the module is bundled that causes it to not get imported correctly by `ngc`.

**Comment by Stabzs** [comment]
@dagstuan Thanks for the confirmation and the investigative work.

I'll look into it.

**Comment by jcannata** [comment]
I am also having trouble with lazy-loaded routes but the error may point to the problem...

`core.umd.js:5995 EXCEPTION: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

Looking at the code it looks like ToasterModule is importing BrowserModule where it probably should be importing CommonModule...

**Comment by Stabzs** [comment]
@jcannata That is a really good catch.

I didn't notice that BrowserModule was used during the code review for the ngModule contribution.

In hindsight, it makes perfect sense that this would be causing issues, since BrowserModule is needed for the entrance to the application, whereas CommonModule is needed for bootstrapping a plugin, which is what this is.  

The library will always be dropped into another application for consumption.  I'll take a close look at this locally.  Thanks.

**Comment by Stabzs** [comment]
Is anyone able to confirm via getting latest source (not package) that the above commit has resolved this issue?  I'd love confirmation before pushing a new npm package version.

Thanks.

**Comment by Stabzs** [comment]
This is now published to NPM as `0.5.1-rc.6`.  Thanks @jcannata for the confirmation!!
