### ISSUE TITLE
AOT mode is not supported

### ISSUE THREAD

**Issue by reflog** [Stabzs/Angular2-Toaster#62]
When using 'ngc', the following error is thrown:

```
Error at /home/reflog/app/src/node_modules/angular2-toaster/lib/toast.component.ngfactory.ts:233:40: Property 'bodyOutputType' is private and only accessible within class 'ToastComponent'.
Error at /home/reflog/app/src/node_modules/angular2-toaster/lib/toast.component.ngfactory.ts:238:40: Property 'bodyOutputType' is private and only accessible within class 'ToastComponent'.
Error at /home/reflog/app/src/node_modules/angular2-toaster/lib/toast.component.ngfactory.ts:243:40: Property 'bodyOutputType' is private and only accessible within class 'ToastComponent'.
```

**Comment by Stabzs** [comment]
@reflog This is really interesting...it would seem that AoT disallows private properties being referenced in pre-compiled templates.  It would _**seem**_ that if a property is exposed to the template in an AoT compilation scenario, it HAS to be public, per https://github.com/angular/angular/issues/11422.  While this does make sense, it also isn't exactly intuitive per se and it is a bit disappointing from an encapsulation perspective, since now internal details/bindings need to be exposed for pre-compilation.

I'll dig for a more elegant solution, but barring one, `bodyOutputType` will be made public.  Thanks.

**Comment by BrainCrumbz** [comment]
Although, having also experience in WPF/C#, it does make sense. From the testing & design point of view, at least, you can think of component view being separated from component logic. Binding between them is a clear interface, so it sounds more normal if that's public. And you want to unit test component logic by inspecting values on its bound properties after some stimuli.

**Comment by Stabzs** [comment]
@BrainCrumbz I don't disagree that this makes sense from a compiled perspective.  I just found it somewhat surprising that an internal template binding needs to be exposed and that ngc doesn't perform a form of hoisting/wrapping to expose those bindings.  That said, of course it simply makes far more sense to require it to be public :)
