### ISSUE TITLE
Support preventing duplicates 

### ISSUE THREAD

**Issue by Birowsky** [Stabzs/Angular2-Toaster#74]
Ideally: if same content toast arrives, just extend the display time of the existing one.

**Comment by Stabzs** [comment]
The title of this issue is misleading. 

Support for duplicates already exists. If the toaster-config preventDuplicates flag is set to false, duplicate toasts can and will be added. 

However, what you are proposing is different and honestly, I have a hard time believing that that is a common use case. When would you need to extend an already displayed toast?

**Comment by Birowsky** [comment]
preventDuplicates is enough for me for now. You can close this.

About my ideal way to handle this:
- prevent duplicates is enabled.
- event a) happens and triggers toast.
- the same event happens 1ms before the toast times out and is closed. If we don't extend the toast time, it would seem that the latest event closed the toast.

**Comment by Stabzs** [comment]
I understand how that scenario would be misleading. I feel like it is probably rare, but it IS possible. 

I'll close this for the time being. If it needs to be looked at again down the road, feel free to reopen.
